### PR TITLE
Extendi

### PR DESCRIPTION
**Pull request by dugjason**
### Added
* Support for [Open Data Processing](https://datasift.com/products/open-data-processing-for-twitter/) batch uploads (Thanks @giovannelli)
* Explicit supprot for 413 and 422 errors from API
* Ability to get at API response headers using the ```object.response``` accessor. (Thanks again @giovannelli)

### Changed
* Bumped [rest-client](https://github.com/rest-client/rest-client) dependency to ~> 1.8

### CODE REVIEW

**Comment by dugjason** [comment]
@giovannelli I'd really appreciate it if you could find a minute next week to review these changes as I've changed a little bit of your original PR from #76.
The most significant change is renaming the class from ```IngestionService``` to ```Odp``` to fit with DataSift's product naming.
Thanks again for your PR; we really appreciate your work

**Comment by giovannelli** [comment]
@dugjason feel free to contact me next week, a quick Skype chat if is ok with you.
Thank you!

**Comment by dugjason** [comment]
Hey @giovannelli I'm free most of this afternoon, and most of the day tomorrow if you still want to catch up about this?

**Comment by giovannelli** [comment]
Hi Jason,
I've added you on Skype. I'll call you at 3pm uk time, is ok with you?

Best

Duccio

On Thursday, August 20, 2015, Jason Dugdale <notifications@github.com>
wrote:

> Hey @giovannelli <https://github.com/giovannelli> I'm free most of this
> afternoon, and most of the day tomorrow if you still want to catch up about
> this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datasift/datasift-ruby/pull/78#issuecomment-132946543>
> .
>


-- 
-- 
Ing. Duccio Giovannelli
Extendi Team - http://www.extendi.it/
See also: http://budgetup.com/ | http://www.recipefy.com/

**Comment by dugjason** [comment]
Yep - thats perfect. I've not received a connection request from you yet

**Comment by giovannelli** [comment]
Hi Jason,
I sent the request last Tuesday! Here's my skype username:
ducciogiovannelli.

Best

Duccio


On 20 August 2015 at 11:28, Jason Dugdale <notifications@github.com> wrote:

> Yep - thats perfect. I've not received a connection request from you yet
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datasift/datasift-ruby/pull/78#issuecomment-132951666>
> .
>



-- 
-- 
Ing. Duccio Giovannelli
Extendi Team - http://www.extendi.it/
See also: http://budgetup.com/ | http://www.recipefy.com/

**Comment by dugjason** [comment]
Hey @giovannelli my [latest commit](https://github.com/datasift/datasift-ruby/commit/d250927f14e38936c95d64b4733118992bac8730) does the work we spoke about earlier; we no longer set the global default SSL version for OpenSSL; the SSL version you choose to use in the gem will default to TLSv1.2 (for Ruby 2.0+), or TLSv1 (if using Ruby 1.x), or will be set to the SSL version specified in the ```ssl_version``` config object value if specified.

**Pull request merged**
